// HOtherColor.h
// Generated by Interface Elements (Window v2.0) on Apr 5 1998
// This is a user written class and will not be overwritten.

#ifndef _HOtherColor_H_
#define _HOtherColor_H_

#include <Window.h>
#include <TextView.h>
#include <ColorControl.h>

//////   Button Messages
enum {
	IE_HOtherColor_FINDBTN = 0x35L,
	IE_HOtherColor_NEXTBTN = 0x33L,
	IE_HOtherColor_ALLBTN = 0x3AL,
	M_OTHER_COLOR_SELECT = 0x3BL
};

#define APPLY_MSG "Apply"
#define CLOSE_MSG "Close"

class HOtherColor : public BWindow
{
public:
					HOtherColor(BRect rect);
		virtual		~HOtherColor(void);
			void	SetTargetWindow(BWindow *in,BHandler *inH){fTarget =in; fHandler = inH;}
			void	SetColor(rgb_color incolor);

protected:
	virtual void 	MessageReceived(BMessage *message);

private:
	BTextView 			*view;
	BColorControl		*palette;
	BView				*sample;
	BWindow				*fTarget;
	BHandler 			*fHandler;
};

#endif
